export const projects = [
  {
    title: "VSV Legal Chambers",
    tag: "LAW FIRM",
    desc: "Comprehensive digital presence for a high-court advocate. Featuring automated consultation scheduling and a high-performance practice-area repository built on Next.js.",
    image: "assets/images/projects/vsv-legal.svg",
    link: "https://www.vsvlegalchambers.com/",
    status: "live",
    span: 7,
  },
  {
    title: "TechBar",
    tag: "E-COMMERCE",
    desc: "Enterprise-grade e-commerce storefront for a European electronics retailer. Integrated with Klarna and a custom repair-tracking system for seamless retail operations.",
    image: "assets/images/projects/techbar.svg",
    link: "https://www.techbar.store/",
    status: "live",
    span: 5,
  },
  {
    title: "AC BuildTech",
    tag: "CONSTRUCTION",
    desc: "High-fidelity corporate portfolio for a construction firm. Showcasing 15+ large-scale residential and commercial developments with a focus on technical precision.",
    image: "assets/images/projects/acbuildtech.svg",
    link: "https://acbuildtechltd.com/",
    status: "live",
    span: 12,
  },
  {
    title: "CRM",
    tag: "COMING SOON",
    desc: "",
    image: "",
    link: "",
    status: "soon",
    span: 6,
  },
  {
    title: "Factory Agentic System",
    tag: "COMING SOON",
    desc: "",
    image: "",
    link: "",
    status: "soon",
    span: 6,
  },
];
