export const projects = [
  {
    title: "VSV Legal Chambers",
    tag: "LAW FIRM",
    desc: "Multi-office site for a Punjab and Haryana High Court advocate - practice areas, consultation booking, and a blog.",
    image: "assets/images/projects/vsv-legal.svg",
    link: "https://www.vsvlegalchambers.com/",
    status: "live",
    span: 7,
  },
  {
    title: "TechBar",
    tag: "E-COMMERCE",
    desc: "Next.js storefront for a Portugal-based electronics retailer - categories, cart, Klarna pay-later, and repair booking.",
    image: "assets/images/projects/techbar.svg",
    link: "https://www.techbar.store/",
    status: "live",
    span: 5,
  },
  {
    title: "AC BuildTech",
    tag: "CONSTRUCTION",
    desc: "Corporate site for a construction company - 15+ project portfolio, services, and team pages.",
    image: "assets/images/projects/acbuildtech.svg",
    link: "https://acbuildtechltd.com/",
    status: "live",
    span: 12,
  },
  {
    title: "CRM",
    tag: "IN PROGRESS",
    desc: "",
    image: "",
    link: "",
    status: "soon",
    span: 6,
  },
  {
    title: "Factory Agentic System",
    tag: "IN PROGRESS",
    desc: "",
    image: "",
    link: "",
    status: "soon",
    span: 6,
  },
];
