export const projects = [
  {
    title: "VSV Legal Chambers",
    tag: "LAW FIRM",
    desc: "Legal site for a Punjab and Haryana High Court practice. Practice areas, consultation flow, and publishing.",
    image: "assets/images/projects/vsv-legal.svg",
    link: "https://www.vsvlegalchambers.com/",
    status: "live",
    span: 7,
  },
  {
    title: "TechBar",
    tag: "E-COMMERCE",
    desc: "Storefront for a Portugal-based electronics retailer. Browsing, cart flow, pay-later checkout, and repair booking.",
    image: "assets/images/projects/techbar.svg",
    link: "https://www.techbar.store/",
    status: "live",
    span: 5,
  },
  {
    title: "AC BuildTech",
    tag: "CONSTRUCTION",
    desc: "Corporate site for a construction firm. Project archive, services, and team pages.",
    image: "assets/images/projects/acbuildtech.svg",
    link: "https://acbuildtechltd.com/",
    status: "live",
    span: 12,
  },
  {
    title: "CRM",
    tag: "COMING SOON",
    desc: "",
    image: "",
    link: "",
    status: "soon",
    span: 6,
  },
  {
    title: "Factory Agentic System",
    tag: "COMING SOON",
    desc: "",
    image: "",
    link: "",
    status: "soon",
    span: 6,
  },
];
